# Generated by Django 3.0.6 on 2020-05-20 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sneakerImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sneaker_class', models.CharField(max_length=100, verbose_name='class of this shoe given by sequential model')),
                ('sneaker_image', models.ImageField(upload_to='shoes', verbose_name='image file for this shoe')),
                ('sneaker_image_name', models.CharField(max_length=200, verbose_name='name of image file for this shoe')),
                ('prediction_valid', models.BooleanField(verbose_name='user validation of prediction from model')),
                ('prediction_validated', models.BooleanField(verbose_name='if prediction for image has been validated by user')),
            ],
        ),
    ]
